version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/el-jobs-poc-sever/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
   ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
