version: 0.0
os: linux
files:
  - source: ./scripts/*
    destination: /var/www/el-jobs-poc-sever/scripts
hooks:
  BeforeInstall:
    - location: ./before-install.sh
      timeout: 300
      runas: root
   ApplicationStart:
    - location: ./start_app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./stop_app.sh
      timeout: 300
      runas: root
