version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing NPM dependencies
      - npm install
  build:
    commands:
      - echo Build the server app
      - npm run build:server
  post_build:
    commands:
      - echo App built
artifacts:
  files:
    - 'dist/apps/api/main.js'
