version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing NPM dependencies
      - npm install
  build:
    commands:
      - echo Build the server app
      - npm run build:server
  post_build:
    commands:
      - echo Prepare bundle
      - mkdir dist/bundle
      - cp package-server.json dist/bundle/package.json
      - cp dist/apps/api/main.js dist/bundle/main.js
      - cp appspec.yml dist/bundle/main.js

artifacts:
  files:
    - 'dist/bundle/*.*'
  name: el-jobs-server-bundle-$(date +%Y-%m-%d)
  discard-paths: yes
