version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing NPM dependencies
      - npm install
  build:
    commands:
      - echo Build the app
      - npm run build
  post_build:
    commands:
      - echo App built
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/apps/api*'
  discard-paths: yes
